/**
 * Rebuilds src/pairTokens.ts from the factory's PairTokenApprovalUpdated logs. The factory keeps approvals
 * in a mapping, so logs are the only way to enumerate them; the wizard re-checks `approvedPairTokens` live.
 *
 *   pnpm --filter @hood/shared sync:pairs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createPublicClient, erc20Abi, http, parseAbiItem, type Address } from 'viem';
import { PONS_V2, PUBLIC_RPC_MAINNET, ponsFactoryAbi, robinhoodChain } from '../src';

const rpc = process.env.RPC_URL || PUBLIC_RPC_MAINNET;
const client = createPublicClient({
  chain: robinhoodChain(rpc),
  transport: http(rpc, { batch: { batchSize: 20, wait: 20 }, retryCount: 6, retryDelay: 1_500 }),
});

// The public RPC caps eth_getLogs at 10,000,000 blocks per request.
const STEP = 9_999_999n;
const event = parseAbiItem('event PairTokenApprovalUpdated(address indexed pairToken, bool approved)');

function kindOf(symbol: string, name: string): string {
  if (name.endsWith('• Robinhood Token')) return 'stock';
  if (symbol === 'USDG') return 'stable';
  if (symbol === 'cbBTC') return 'crypto';
  return 'other';
}

async function main() {
  const latest = await client.getBlockNumber();
  const approved = new Map<Address, boolean>();
  for (let from = 0n; from <= latest; from += STEP + 1n) {
    const to = from + STEP > latest ? latest : from + STEP;
    const logs = await client.getLogs({ address: PONS_V2.launchFactory, event, fromBlock: from, toBlock: to });
    for (const l of logs) approved.set(l.args.pairToken!, l.args.approved!);
  }

  const rows: string[] = [];
  for (const [address, ok] of approved) {
    if (!ok) continue;
    const [symbol, name, decimals, live] = await Promise.all([
      client.readContract({ address, abi: erc20Abi, functionName: 'symbol' }),
      client.readContract({ address, abi: erc20Abi, functionName: 'name' }),
      client.readContract({ address, abi: erc20Abi, functionName: 'decimals' }),
      client.readContract({ address: PONS_V2.launchFactory, abi: ponsFactoryAbi, functionName: 'approvedPairTokens', args: [address] }),
    ]);
    if (!live) continue;
    const label = name.replace(/\s*•\s*Robinhood Token$/, '');
    rows.push(`  { address: '${address}', symbol: ${JSON.stringify(symbol)}, name: ${JSON.stringify(label)}, decimals: ${decimals}, kind: '${kindOf(symbol, name)}' },`);
  }

  const out = `// Generated by \`pnpm --filter @hood/shared sync:pairs\` on ${new Date().toISOString().slice(0, 10)} (block ${latest}). Do not edit.
import type { PairToken } from './pairs';

export const PAIR_TOKENS: readonly PairToken[] = [
${rows.join('\n')}
];
`;
  const path = fileURLToPath(new URL('../src/pairTokens.ts', import.meta.url));
  writeFileSync(path, out);
  console.log(`wrote ${rows.length} pair tokens to ${path}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
