'use client';

import type { ReactNode } from 'react';
import { Button } from '@/components/xp/Button';
import { WarningIcon } from '@/components/xp/Icons';
import { openApp } from '@/lib/openApp';
import { useRisk } from '@/lib/risk';
import { useWindows, type WindowState } from '@/store/windows';
import shared from '../apps.module.css';
import styles from './Legal.module.css';

/**
 * Drafts written from docs/BRIEF.md §5.10, not yet reviewed by a lawyer. Flip to false once Bix's
 * counsel signs off on the text (and fill in CONTACT); until then each window says it is a draft.
 */
export const LEGAL_DRAFT = true;
export const LEGAL_UPDATED = '9 October 2026';
const OPERATOR = 'Wealthy People';
const CONTACT: string | null = null;

/** The points the one-time risk dialog shows before a first launch or trade. */
export const RISK_POINTS: ReactNode[] = [
  <>
    <b>Memecoins can go to zero.</b> Most coins lose most or all of their value. Only use money you can afford to lose.
  </>,
  <>
    <b>Most launches never graduate.</b> A coin that never fills its curve stays on it, often with almost no buyers.
  </>,
  <>
    <b>Launches and trades are irreversible.</b> Launch settings can never be changed, and a confirmed transaction can&apos;t be undone or refunded.
  </>,
  <>
    <b>Pons V2 is unaudited.</b> Launches and trades run on third-party smart contracts that have not been audited and may contain bugs.
  </>,
  <>
    <b>Rigor scores aren&apos;t proofs or advice.</b> They are an AI estimate of a statement, not a check of any proof and not a reason to buy.
  </>,
];

function Doc({ title, children, win }: { title: string; children: ReactNode; win: WindowState }) {
  return (
    <>
      <div className={`${shared.pane} ${shared.white} ${styles.doc}`}>
        <h1>{title}</h1>
        <p className={styles.updated}>Last updated {LEGAL_UPDATED}</p>
        {LEGAL_DRAFT && <p className={styles.draft}>Draft pending legal review. The final text may differ.</p>}
        {children}
        <p className={styles.contact}>
          Questions: {CONTACT ?? 'contact details will be published here before launch.'} hood.exe is not affiliated with Robinhood Markets, Inc. or with Pons.
        </p>
      </div>
      <div className={shared.footerRow}>
        <Button onClick={() => useWindows.getState().close(win.id)}>Close</Button>
      </div>
    </>
  );
}

const Link = ({ to, children }: { to: 'terms' | 'risk' | 'privacy'; children: ReactNode }) => (
  <button type="button" className={styles.link} onClick={() => openApp(to)}>
    {children}
  </button>
);

export function Terms({ win }: { win: WindowState }) {
  return (
    <Doc title="Terms of Use" win={win}>
      <p>
        These terms cover your use of hood.exe (the website and its API), operated by {OPERATOR} (&quot;we&quot;). By using hood.exe you agree to them. If you
        don&apos;t agree, don&apos;t use it.
      </p>
      <h2>1. What hood.exe is</h2>
      <p>
        hood.exe is a non-custodial interface to the Pons V2 launchpad on Robinhood Chain. We never hold your funds or keys. Every launch and trade is a
        transaction you sign in your own wallet and is carried out by smart contracts that we did not write and do not control.
      </p>
      <h2>2. Who may use it</h2>
      <p>
        You must be of legal age where you live and allowed to use services like this there. You may not use hood.exe if you are subject to sanctions or
        live in a place where doing so is unlawful. You are responsible for following your local laws and for any taxes.
      </p>
      <h2>3. Launching a coin</h2>
      <p>
        You are responsible for everything you publish: name, ticker, logo, theorem, description and links. That content is stored on IPFS and on-chain,
        so it is public and permanent. We can hide it from hood.exe but cannot delete it from the chain. Don&apos;t publish anything unlawful, infringing,
        hateful, sexual, deceptive or that impersonates someone else.
      </p>
      <h2>4. Rigor scores</h2>
      <p>Rigor scores are generated by an AI model. They estimate how well-formed and significant a statement is. They don&apos;t verify any proof and are not advice.</p>
      <h2>5. Callouts</h2>
      <p>
        Callouts are public posts by users, not by us. Posts are checked automatically and may be hidden. We may hide any post and restrict any wallet,
        for example for spam, scams, harassment or links. Don&apos;t post anything you wouldn&apos;t want public forever.
      </p>
      <h2>6. Fees</h2>
      <p>
        Pons charges a launch fee, trade fees, creator taxes and, early on, snipe taxes. They are shown before you sign. hood.exe currently adds no fee of
        its own; if that changes, these terms will say so first.
      </p>
      <h2>7. No advice, no endorsement</h2>
      <p>
        Nothing on hood.exe is financial, investment, legal or tax advice. Listing a coin is not an endorsement of it or of its creator. Read the{' '}
        <Link to="risk">Risk disclosure</Link>.
      </p>
      <h2>8. No warranty, limited liability</h2>
      <p>
        hood.exe is provided &quot;as is&quot;, without warranties of any kind. It may be unavailable, slow or wrong, including prices, balances and P&amp;L.
        To the extent the law allows, we are not liable for losses from your use of hood.exe, from smart contracts, wallets, networks or other third
        parties, or from coins you buy, sell or launch.
      </p>
      <h2>9. Changes</h2>
      <p>We may change hood.exe or these terms, or stop offering hood.exe, at any time. The date above shows the latest version.</p>
      <p>
        See also the <Link to="privacy">Privacy notice</Link>.
      </p>
    </Doc>
  );
}

export function Risk({ win }: { win: WindowState }) {
  const accepted = useRisk((s) => s.accepted);
  return (
    <Doc title="Risk disclosure" win={win}>
      <div className={styles.callout}>
        <WarningIcon size={24} />
        <p>Trading and launching memecoins is highly speculative. You can lose everything you put in.</p>
      </div>
      <ul className={styles.points}>
        {RISK_POINTS.map((p, i) => (
          <li key={i}>{p}</li>
        ))}
        <li>
          <b>Prices move fast and liquidity can disappear.</b> Curve prices change with every trade; a large sell or a graduation can move them sharply.
          Slippage limits protect you only up to the tolerance you set.
        </li>
        <li>
          <b>Snipe taxes and creator taxes apply.</b> Early buyers can pay a high snipe tax, and creators can set taxes on trades. Check the estimate
          before you sign.
        </li>
        <li>
          <b>Anyone can launch a coin.</b> Names, logos and theorems are chosen by their creators and may be misleading. A coin is not affiliated with
          any person, company or result it names.
        </li>
        <li>
          <b>Your wallet is your responsibility.</b> Lost keys can&apos;t be recovered, and transactions signed by a compromised wallet can&apos;t be
          reversed. hood.exe will never ask for your seed phrase.
        </li>
        <li>
          <b>Networks and services fail.</b> Robinhood Chain, RPC providers, the indexer or hood.exe itself can be down or behind. What hood.exe shows
          may be out of date.
        </li>
        <li>
          <b>Rules can change.</b> Laws on crypto assets differ by country and change often. Some coins may be unlawful to buy or sell where you live.
        </li>
      </ul>
      {accepted && <p className={styles.updated}>You accepted this disclosure in this browser.</p>}
    </Doc>
  );
}

export function Privacy({ win }: { win: WindowState }) {
  return (
    <Doc title="Privacy notice" win={win}>
      <p>This notice explains what hood.exe ({OPERATOR}) handles about you and why. We don&apos;t sell personal data.</p>
      <h2>Public by design</h2>
      <p>
        Your wallet address, launches, trades and balances are public on Robinhood Chain. Launch metadata (logo, theorem, description) is public on IPFS.
        Callouts, reactions and nicknames are shown to everyone. None of this can be erased from the chain or IPFS.
      </p>
      <h2>What we store</h2>
      <ul className={styles.points}>
        <li>
          <b>Sign-in:</b> your wallet address and a session cookie when you sign in with Ethereum, for up to 7 days.
        </li>
        <li>
          <b>Your posts:</b> callouts, reactions and nickname, linked to your wallet, including posts our moderation hides.
        </li>
        <li>
          <b>Theorems:</b> statements you score and their rigor results, so the same statement isn&apos;t scored twice.
        </li>
        <li>
          <b>IP addresses:</b> used to rate-limit sign-ins, scoring and posting (kept for at most an hour for that), and recorded in server logs for
          security and debugging.
        </li>
        <li>
          <b>Usage analytics:</b> PostHog records which windows and features are used, whether launches and trades succeed,
          errors and page speed, under an anonymous ID that lasts only for your visit. It never receives your wallet address
          or anything you type, and doesn&apos;t record your screen.
        </li>
        <li>
          <b>In your browser:</b> local storage remembers preferences such as tray balloons, your wallet connection and that you accepted the risk
          disclosure.
        </li>
      </ul>
      <h2>Who processes it</h2>
      <p>
        DeepSeek&apos;s AI processes the text of theorems you score and of callouts you post (for rigor scoring and moderation), and may process it outside
        your country. Pinata publishes launch metadata to IPFS. Our hosting, database, indexer and RPC providers (Vercel, Railway, Envio, Alchemy) process
        requests on our behalf. WalletConnect (Reown) relays wallet connections if you use it.
      </p>
      <h2>Your choices</h2>
      <p>
        You can browse without connecting a wallet. You can sign out at any time (Start → Log Off). To have your nickname or callouts removed from
        hood.exe, contact us; on-chain and IPFS data can&apos;t be removed. See also the <Link to="terms">Terms of Use</Link>.
      </p>
    </Doc>
  );
}
